	location = /healthcheck {

	    allow 127.0.0.1;
	    allow ::1;
	    allow 94.50.161.126/32;
	    allow 51.144.77.42/32;
	    allow 178.70.48.51/32;
	    allow 188.16.101.159/32;
	    allow 46.146.28.138/32;
	    allow 178.121.75.173/32;
	    allow 31.163.252.49/32;
	    allow 37.131.205.246/32;
	    allow 10.121.0.0/16;
	    deny all;

	    default_type text/plain;
	    content_by_lua_block {
		local hc = require "resty.upstream.healthcheck"
		ngx.say("Nginx Worker PID: ", ngx.worker.pid())
		ngx.print(hc.status_page())
	    }
	}
