import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id "com.gradleup.shadow" version "8.3.2"
}

dependencies {
    compileOnly "org.keycloak:keycloak-quarkus-server-app:$keycloakVersion"

    implementation(platform("io.quarkus:quarkus-bom:$quarkusVersion"))
    implementation ("com.fasterxml.jackson.dataformat:jackson-dataformat-xml") {
        exclude group: 'com.fasterxml.jackson.core', module: 'jackson-annotations'
        exclude group: 'com.fasterxml.jackson.core', module: 'jackson-core'
        exclude group: 'com.fasterxml.jackson.core', module: 'jackson-databind'
        exclude group: 'net.bytebuddy', module: 'byte-buddy'
    }

    implementation(
            project(":sso-business-logic"),
            project(":tbapi-remote-service"),
            project(":custom-jpa-provider"),
    )

    testImplementation "org.keycloak:keycloak-quarkus-server-app:$keycloakVersion"
}

processResources {
    def hash = new Date().format('yyyyMMddHHmmss')
    with copySpec {
        from 'src/main/resources'
        include 'themes/*/login/template.ftl'
        duplicatesStrategy DuplicatesStrategy.INCLUDE
        filter(ReplaceTokens, tokens: [hash: hash])
    }
}

shadowJar {
    manifest {
        attributes "Main-Class": "Main"
    }
    mergeServiceFiles()
}

build.dependsOn(shadowJar)
