plugins {
    id 'war'
}

dependencies {

    implementation (
            project(':sso-business-logic'),
            project(':tbapi-remote-service'),
    )

    providedCompile "org.keycloak:keycloak-core:$keycloakVersion"
    providedCompile "org.keycloak:keycloak-services:$keycloakVersion"
    providedCompile "org.keycloak:keycloak-server-spi:$keycloakVersion"
    providedCompile "org.keycloak:keycloak-server-spi-private:$keycloakVersion"
    providedCompile "org.keycloak:keycloak-model-jpa:$keycloakVersion"
    providedCompile group: 'javax', name: 'javaee-api', version: '8.0.1'

    providedCompile 'org.slf4j:slf4j-api:1.7.22'

    // https://mvnrepository.com/artifact/javax.ejb/ejb-api
//    providedCompile group: 'javax.ejb', name: 'ejb-api', version: '3.0'

}