variables:
  GIT_STRATEGY: fetch
  BASE_DIR: /opt/gitlab-ci
  REGISTRY: registry.alamics.ru

stages:
  - compile
  - test
  - bundle
  - build
  - deploy

back:compile:
  stage: compile
#  when: manual
  except:
    - master
  script:
    - ./gradlew :classes -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/

back:test:
  stage: test
  when: on_success
  except:
    - master
  script:
    - ./gradlew :check -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/**/reports
    reports:
      junit: build/test-results/**/TEST-*.xml

back:war:
  stage: bundle
  when: on_success
  except:
    - master
  script:
    - ./gradlew :bundle -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    paths:
      - build/bundle/*.war
    name: "domru-sso"
    expire_in: 1 week

#back:docker:
#  stage: build
#  when: on_success
#  script:
#    - mkdir -p .ci_status
#    - $BASE_DIR/scripts/build.sh
#    - touch .ci_status/build_backend
#  artifacts:
#    paths:
#      - .ci_status/
#  only:
#    - develop
#    - /release\/.*/
#    - tags
#  cache:
#    key: "$CI_COMMIT_SHA"
#    paths:
#      - .gradle/
#      - backend/build/
#    policy: pull
#
#back:dpl:test:
#  stage: deploy
#  when: on_success
#  environment:
#    name: test
#  only:
#    - develop
#  script:
#    - if [ ! -f .ci_status/build_backend ]; then exit 1; fi
#    - $BASE_DIR/scripts/deploy.sh
#  artifacts:
#    paths:
#      - .ci_status/
#
#back:dpl:stage:
#  stage: deploy
#  when: on_success
#  environment:
#    name: prerelease
#  only:
#    - /release\/.*/
#  script:
#    - if [ ! -f .ci_status/build_backend ]; then exit 1; fi
#    - $BASE_DIR/scripts/deploy.sh
#  artifacts:
#    paths:
#      - .ci_status/

#back:dpl:prod:
#  stage: deploy
#  when: on_success
#  environment:
#    name: production
#  only:
#    - tags
#  script:
#    - if [ ! -f .ci_status/build_backend ]; then exit 1; fi
#    - $BASE_DIR/scripts/deploy.sh
#  artifacts:
#    paths:
#      - .ci_status/
