variables:
  GIT_STRATEGY: fetch
  BASE_DIR: /opt/gitlab-ci
  REGISTRY: registry.alamics.ru

stages:
  - compile
  - test
  - build
  - createwar
  - docker
  - deploy

back:compile:
  stage: compile
  except:
    - master
  script:
    - ./gradlew :classes --stacktrace -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache: {}

back:compile:1.8:
  stage: compile
  except:
    - master
  script:
    - ./gradlew :classes --stacktrace -Dorg.gradle.java.home=/usr/java/jdk1.8.0
  cache: {}

back:test:adapter:tbapi-remote-service:
  stage: test
  when: on_success
  except:
    - master
  script:
    - ./gradlew :tbapi-remote-service:check -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/tbapi-remote-service/reports
    name: "tbapi-remote-service-test-reports-$CI_PIPELINE_ID"
    reports:
      junit: build/test-results/tbapi-remote-service/TEST-*.xml

back:test:adp:tbapi-remote-service:1.8:
  stage: test
  when: on_success
  needs: ["back:compile:1.8"]
  except:
    - master
  script:
    - ./gradlew :tbapi-remote-service:check -Dorg.gradle.java.home=/usr/java/jdk1.8.0
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/tbapi-remote-service/reports
    name: "tbapi-remote-service-test-reports-$CI_PIPELINE_ID"
    reports:
      junit: build/test-results/tbapi-remote-service/TEST-*.xml

back:test:sso-business-logic:
  stage: test
  when: on_success
  except:
    - master
  script:
    - ./gradlew :sso-business-logic:check -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/sso-business-logic/reports
    name: "sso-business-logic-test-reports-$CI_PIPELINE_ID"
    reports:
      junit: build/test-results/sso-business-logic/TEST-*.xml

back:test:sso-business-logic:1.8:
  stage: test
  when: on_success
  needs: ["back:test:adp:tbapi-remote-service:1.8"]
  except:
    - master
  script:
    - ./gradlew :sso-business-logic:check -Dorg.gradle.java.home=/usr/java/jdk1.8.0
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/sso-business-logic/reports
    name: "sso-business-logic-test-reports-$CI_PIPELINE_ID"
    reports:
      junit: build/test-results/sso-business-logic/TEST-*.xml

back:test:keycloak-extension:
  stage: test
  when: on_success
  except:
    - master
  script:
    - ./gradlew :keycloak-extension:check -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/keycloak-extension/reports
    name: "keycloak-extension-test-reports-$CI_PIPELINE_ID"
    reports:
      junit: build/test-results/keycloak-extension/TEST-*.xml

back:test:keycloak-extension:1.8:
  stage: test
  when: on_success
  needs: ["back:test:sso-business-logic:1.8"]
  except:
    - master
  script:
    - ./gradlew :keycloak-extension:check -Dorg.gradle.java.home=/usr/java/jdk1.8.0
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
    policy: pull
  artifacts:
    when: always
    paths:
      - build/test-results/keycloak-extension/reports
    name: "keycloak-extension-test-reports-$CI_PIPELINE_ID"
    reports:
      junit: build/test-results/keycloak-extension/TEST-*.xml

back:war:
  stage: build
  when: on_success
  except:
    - master
  script:
    - currentdir=`pwd`
    - cd keycloak-extension/src/main/resources/themes/domru/login/resources
    - npm install
    - npm run build
    - rm -rf node_modules
    - cd $currentdir
    - mkdir -p .ci_status
    - ./gradlew :deploy -Dorg.gradle.java.home=/usr/java/jdk-11.0.2
    - touch .ci_status/war_built
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
  artifacts:
    paths:
      - .ci_status/
      - build/**/libs/*.war
      - build/**/libs/*.jar
      - build/deploy/
      - tools/module.xml
    name: "domru-sso-compile-$CI_PIPELINE_ID"
    expire_in: 1 week

back:war:1.8:
  stage: build
  when: on_success
  needs: ["back:test:keycloak-extension:1.8"]
  except:
    - master
  script:
    - currentdir=`pwd`
    - cd keycloak-extension/src/main/resources/themes/domru/login/resources
    - npm install
    - npm run build
    - rm -rf node_modules
    - cd $currentdir
    - mkdir -p .ci_status
    - ./gradlew :deploy -Dorg.gradle.java.home=/usr/java/jdk1.8.0
    - touch .ci_status/war_built
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .gradle/
      - build/
  artifacts:
    paths:
      - .ci_status/
      - build/**/libs/*.war
      - build/**/libs/*.jar
      - build/deploy/
      - tools/module.xml
    name: "domru-sso-compile-$CI_PIPELINE_ID"
    expire_in: 1 week

container:source:
  stage: docker
  when: manual
  script:
    - $BASE_DIR/scripts/build.sh
  artifacts:
    paths:
      - .ci_status/

container:domain:
  stage: docker
  when: manual
  script:
    - $BASE_DIR/scripts/build.sh
  artifacts:
    paths:
      - .ci_status/

container:
  stage: docker
  when: manual
  script:
    - $BASE_DIR/scripts/build.sh
  artifacts:
    paths:
      - .ci_status/

dpl:devel:domain:
  stage: deploy
  when: manual
  environment:
    name: devel
    url: http://domru-sso-devel-domain.dev.itrev.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:devel:domwar:
  stage: deploy
  when: manual
  environment:
    name: devel
    url: http://domru-sso-devel-domain.dev.itrev.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:devel:
  stage: deploy
  when: manual
  environment:
    name: devel
    url: http://domru-sso.alamics.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:test:
  stage: deploy
  when: manual
  environment:
    name: test
    url: http://domru-sso-test.alamics.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:test:battle:
  stage: deploy
  when: manual
  environment:
    name: test
    url: http://domru-sso-test.alamics.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:stage:
  stage: deploy
  when: manual
  only:
    - tags
  environment:
    name: stage
    url: http://domru-sso-stage.alamics.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:stage2:
  stage: deploy
  when: manual
  only:
    - tags
  environment:
    name: stage
    url: http://domru-sso-stage1.alamics.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:stage3:
  stage: deploy
  when: manual
  only:
    - tags
  environment:
    name: stage
    url: http://domru-sso-stage2.alamics.ru
  script:
    - $BASE_DIR/scripts/deploy.sh

dpl:prod:
  stage: deploy
  when: manual
  environment:
    name: stage
    url: http://sso.dev.itrev.ru
  script:
    - scp build/deploy/standalone/deployments/custom-jpa.jar sso-app02:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp tools/module.xml sso-app02:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp build/deploy/standalone/deployments/custom-jpa.jar sso-app03:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp tools/module.xml sso-app03:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp build/deploy/standalone/deployments/custom-jpa.jar sso-app04:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp tools/module.xml sso-app04:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp build/deploy/standalone/deployments/custom-jpa.jar sso-app05:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - scp tools/module.xml sso-app05:/usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - cp build/deploy/standalone/deployments/custom-jpa.jar /usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - cp tools/module.xml /usr/local/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
    - /usr/local/keycloak/bin/jboss-cli.sh --connect --user=admin --password=addMin --command="deploy --all-server-groups build/deploy/standalone/deployments/domru-sso.war"
  tags:
    - sso-domain-controller
