variables:
  GIT_STRATEGY: fetch
  BASE_DIR: /opt/gitlab-ci

stages:
  - compile
  - test
  - build
  - createwar
  - docker
  - deploy

.init_vars: &init-variables
  before_script:
  - cp ${ERTK_PEM} configs/ertk.pem
  - envsubst < configs/sso.tmpl > configs/sso

.domru:stage:template:
  stage: deploy
  image: harbor.ertelecom.ru/b2bweb/kubectl-helm:1.24-alpine
  when: manual
  script:
    - export FQDN=`echo "${CI_ENVIRONMENT_URL}" | sed 's/^http\(\|s\):\/\///g'`
    - consul-template -once -template ".helm/values-dev.yaml.tpl:values.yaml"
    - helm upgrade -i ${CI_ENVIRONMENT_SLUG} --values values.yaml ./.helm -n ${NAMESPACE} --atomic --timeout 5m
    - helm history -n ${NAMESPACE} ${CI_ENVIRONMENT_SLUG} --max 5
  tags:
    - sso-build-k8s

.domru:prod:template:
  stage: deploy
  image: harbor.ertelecom.ru/b2bweb/kubectl-helm:1.24-alpine
  when: manual
  only:
    - tags
  script:
    - export FQDN=`echo "${CI_ENVIRONMENT_URL}" | sed 's/^http\(\|s\):\/\///g'`
    - consul-template -once -template ".helm/values-prod.yaml.tpl:values.yaml"
    - cat values.yaml
    - helm upgrade -i ${CI_ENVIRONMENT_SLUG} --values values.yaml ./.helm -n ${NAMESPACE} --atomic --timeout 10m
    - helm history -n ${NAMESPACE} ${CI_ENVIRONMENT_SLUG} --max 5
  variables:
    NAMESPACE: 'sso'
    NODE_PORT: '30080'
    REPLICA_COUNT: '5'

.infinispan:prod:template:
  stage: deploy
  image: harbor.ertelecom.ru/b2bweb/kubectl-helm:1.24-alpine
  when: manual
  script:
    # Apply Infinispan installation manifest
    - kubectl apply -f ./configs/infinispan15/infinispan-${DC}.yaml
    # Apply Infinispan caches manifest
    - kubectl apply -f ./configs/infinispan15/caches-${DC}.yaml

.frontend:theme:build:
  stage: build
  image: harbor.ertelecom.ru/b2bweb/openjdk:21-node20
  script:
    - cd frontend/$BUILD_THEME
    - npm ci --cache ~/.npm --prefer-offline && npm run build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ~/.npm
  artifacts:
    paths:
      - keycloak-extension/src/main/resources/themes/$BUILD_THEME/login/resources/build/
    name: "domru-sso-$CI_PIPELINE_ID"
    expire_in: 1 day
  allow_failure: false
  when: manual
  tags:
    - sso-build-docker

frontend:domru:build:
  extends: .frontend:theme:build
  variables:
    BUILD_THEME: domru

frontend:ertelecom:build:
  extends: .frontend:theme:build
  variables:
    BUILD_THEME: ertelecom

frontend:stelecom:build:
  extends: .frontend:theme:build
  variables:
    BUILD_THEME: stelecom

frontend:novotelecom:build:
  extends: .frontend:theme:build
  variables:
    BUILD_THEME: novotelecom
    
frontend:admin:build:
  stage: build
  image: harbor.ertelecom.ru/b2bweb/openjdk:21-node20
  script:
    - npm i -g pnpm
    - cd frontend-admin
    - pnpm install
    - cd ../frontend-admin/js/apps/admin-ui
    - pnpm run build
  artifacts:
    paths:
      - keycloak-extension/src/main/resources/themes/keycloak.v2/admin/resources/
    name: "domru-sso-$CI_PIPELINE_ID"
    expire_in: 1 day
  allow_failure: false
  when: manual
  tags:
    - sso-build-docker

back:build:
  stage: build
  image: harbor.ertelecom.ru/b2bweb/openjdk:21-node20
  script:
    - gradle --stacktrace --console=plain build
  cache:
    key: "CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/
  artifacts:
    paths:
      - build/keycloak-extension/libs/keycloak-extension-1.0.1-all.jar
    name: "domru-sso-$CI_PIPELINE_ID"
    expire_in: 1 day
  allow_failure: false
  needs:
    - "frontend:domru:build"
    - "frontend:ertelecom:build"
    - "frontend:stelecom:build"
    - "frontend:admin:build"
    - "frontend:novotelecom:build"
  when: manual
  tags:
    - sso-build-docker

container-image:
  stage: docker
  <<: *init-variables
  when: manual
  script:
    - docker build -t harbor.ertelecom.ru/sso-protected/sso:$CI_PIPELINE_ID .
    - docker push harbor.ertelecom.ru/sso-protected/sso:$CI_PIPELINE_ID
  allow_failure: false
  needs:
    - "back:build"
  tags:
    - sso-build-shell

domru:stage:
  extends: .domru:stage:template
  environment:
    name: stage
    url: https://sso-balancer.testing.srv.loc
  variables:
    NAMESPACE: 'sso'
    NODE_PORT: '30081'
    REPLICA_COUNT: '1'

domru:stage2:
  extends: .domru:stage:template
  environment:
    name: stage2
    url: https://sso-balancer2.testing.srv.loc
  variables:
    NAMESPACE: 'sso'
    NODE_PORT: '30082'
    REPLICA_COUNT: '1'
    KC_CACHE_CONFIG_FILE: 'cache-ispn.persistent.xml'
    KC_CACHE_STACK: 'kubernetes'
    KC_FEATURES: 'persistent-user-sessions'

domru:stage3:
  extends: .domru:stage:template
  environment:
    name: stage3
    url: https://sso-balancer3.testing.srv.loc
  variables:
    NAMESPACE: 'sso'
    NODE_PORT: '30083'
    REPLICA_COUNT: '1'

domru:stage4:
  extends: .domru:stage:template
  environment:
    name: stage4
    url: https://sso-balancer4.testing.srv.loc
  variables:
    NAMESPACE: 'sso'
    NODE_PORT: '30084'
    REPLICA_COUNT: '3'
    KC_CACHE_CONFIG_FILE: 'cache-ispn.persistent.xml'
    KC_CACHE_STACK: 'kubernetes'
    KC_FEATURES: 'persistent-user-sessions'

domru:stage5:
  extends: .domru:stage:template
  environment:
    name: stage5
    url: https://sso-balancer5.testing.srv.loc
  variables:
    NAMESPACE: 'sso'
    NODE_PORT: '30085'
    REPLICA_COUNT: '3'
  only:
    - itres # т.к. пока еше не обновлен

infinispan:stage5:
  stage: deploy
  image: harbor.ertelecom.ru/b2bweb/kubectl-helm:1.24-alpine
  when: manual
  variables:
    NAMESPACE: 'sso'
    INFINISPAN_REPLICA_COUNT: '3'
  script:
    - export DTD=$(date | sha256sum)
    - consul-template -once -template "./configs/infinispan/.helm/values-dev.yaml.tpl:values.yaml"
    - ln -s ${INFINISPAN_MGMT_USERS} ./configs/infinispan/.helm/configs/mgmt-users.properties
    - ln -s ${INFINISPAN_MGMT_GROUPS} ./configs/infinispan/.helm/configs/mgmt-groups.properties
    - helm upgrade -i infinispan --values values.yaml ./configs/infinispan/.helm -n ${NAMESPACE} --atomic --timeout 5m
    - helm history -n ${NAMESPACE} infinispan --max 5
  tags:
    - sso-build-k8s
  only:
    - itres # т.к. пока еше не обновлен

domru:perm-k8s:
  extends: .domru:prod:template
  tags:
    - sso-k8s-perm
  environment:
    name: production-k8s-perm
    url: https://auth.dom.ru
  variables:
    KC_CACHE_CONFIG_FILE: 'cache-ispn.persistent.xml'
    KC_CACHE_STACK: 'kubernetes'
    KC_FEATURES: 'persistent-user-sessions'
    DC_NAME: perm

domru:voronezh-k8s:
  extends: .domru:prod:template
  tags:
    - sso-k8s-voronezh
  environment:
    name: production-k8s-voronezh
    url: https://auth.dom.ru
  variables:
    KC_CACHE_CONFIG_FILE: 'cache-ispn.persistent.xml'
    KC_CACHE_STACK: 'kubernetes'
    KC_FEATURES: 'persistent-user-sessions'
    DC_NAME: voronezh

infinispan:stage-k8s:
  extends: .infinispan:prod:template
  variables:
    DC: "stage"
  except:
    - tags
  tags:
    - sso-build-k8s

infinispan:perm-k8s:
  extends: .infinispan:prod:template
  variables:
    DC: "perm"
  only:
    - tags
  tags:
    - sso-k8s-perm

infinispan:voronezh-k8s:
  extends: .infinispan:prod:template
  variables:
    DC: "voronezh"
  only:
    - tags
  tags:
    - sso-k8s-voronezh
