FROM registry.alamics.ru/devops/keycloak/keycloak:6.0.1

RUN cp /opt/jboss/configs/host-master.xml /opt/jboss/keycloak/domain/configuration
RUN cp /opt/jboss/configs/host-slave.xml /opt/jboss/keycloak/domain/configuration

RUN echo "admin=fbfd754b0b0b48b7bbbe7cad57ea7920" > /opt/jboss/keycloak/domain/configuration/mgmt-users.properties
RUN echo "admin=PowerUser,BillingAdmin" > /opt/jboss/keycloak/domain/configuration/mgmt-groups.properties

ENTRYPOINT [ "/opt/jboss/tools/docker-domain-entrypoint.sh" ]
