FROM registry.alamics.ru/devops/keycloak/keycloak:6.0.1

RUN cp /opt/jboss/configs/host-master.xml /opt/jboss/keycloak/domain/configuration
RUN cp /opt/jboss/configs/host-slave.xml /opt/jboss/keycloak/domain/configuration
RUN cp /opt/jboss/configs/domain.xml /opt/jboss/keycloak/domain/configuration

RUN mkdir -p /opt/jboss/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
RUN cp /opt/jboss/build/custom-jpa.jar /opt/jboss/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main
RUN cp /opt/jboss/tools/module.xml /opt/jboss/keycloak/modules/system/layers/base/ru/alamics/sso/jpa/main

RUN mkdir -p /opt/jboss/keycloak/modules/ru/alamics/sso/jpa/main
RUN cp /opt/jboss/build/custom-jpa.jar /opt/jboss/keycloak/modules/ru/alamics/sso/jpa/main
RUN cp /opt/jboss/tools/module.xml /opt/jboss/keycloak/modules/ru/alamics/sso/jpa/main

RUN echo '#$REALM_NAME=ManagementRealm$ This line is used by the add-user utility to identify the realm name already used in this file.' > /opt/jboss/keycloak/domain/configuration/mgmt-users.properties
RUN echo "admin=fbfd754b0b0b48b7bbbe7cad57ea7920" >> /opt/jboss/keycloak/domain/configuration/mgmt-users.properties
RUN echo "admin=PowerUser,BillingAdmin" > /opt/jboss/keycloak/domain/configuration/mgmt-groups.properties

ENTRYPOINT [ "/opt/jboss/tools/docker-domain-entrypoint.sh" ]
