FROM jboss/base-jdk:8

ENV KEYCLOAK_VERSION 6.0.1
ENV JDBC_POSTGRES_VERSION 42.2.5
ENV JDBC_MYSQL_VERSION 5.1.46
ENV JDBC_MARIADB_VERSION 2.2.3

ENV LAUNCH_JBOSS_IN_BACKGROUND 1
ENV PROXY_ADDRESS_FORWARDING false
ENV JBOSS_HOME /opt/jboss/keycloak
ENV LANG en_US.UTF-8

ENV JAVA_OPTS -Djboss.server.default.config=standalone.xml

ARG GIT_REPO
ARG GIT_BRANCH
ARG KEYCLOAK_DIST=https://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

USER root

RUN echo ip_resolve=4 >> /etc/yum.conf
RUN yum update -y && yum install -y epel-release git && yum install -y jq openssl which && yum clean all

RUN mkdir -p /opt/jboss/build
ADD build/deploy/standalone/deployments/custom-jpa.jar /opt/jboss/build
ADD tools /opt/jboss/tools
ADD configs /opt/jboss/configs
RUN chmod 755 /opt/jboss/tools/build-keycloak.sh
RUN /opt/jboss/tools/build-keycloak.sh

USER 1000

EXPOSE 8080
EXPOSE 8443
EXPOSE 9990
EXPOSE 9999

ENTRYPOINT [ "/opt/jboss/tools/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0", "-c=standalone.xml"]
