dependencies {
    implementation (
            project(':sso-business-logic'),
    )

    implementation 'org.jboss.resteasy:resteasy-jaxrs:3.6.3.Final'
    implementation 'org.jboss.resteasy:resteasy-client:3.6.3.Final'
    implementation 'org.jboss.resteasy:resteasy-jackson2-provider:3.6.3.Final'
    implementation 'org.slf4j:slf4j-api:1.7.22'
    implementation group: 'javax.ejb', name: 'ejb-api', version: '3.0'

    testImplementation 'com.github.tomakehurst:wiremock-jre8:2.23.2'
}