version: '3.8'

networks:
  traefik3:
    external: true

services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    networks:
      - traefik3
    environment:
      ServerOptions__Hostname: smtp4dev-er-sso.dev.it-resource.team
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.smtp4dev.basicauth.users=tester:${DOLLAR}${DOLLAR}2y${DOLLAR}${DOLLAR}05${DOLLAR}${DOLLAR}UtcScUwbnflomoB1hhSJ0OpFvOLR6A8QH5ImGo7.QYoBws3qwUo5K" # tester / z3kco5xpZQzenqUEz2Ob
        - "traefik.http.routers.smtp4dev.rule=Host(`smtp4dev-er-sso.dev.it-resource.team`) && PathPrefix(`/`)"
        - "traefik.http.routers.smtp4dev.service=smtp4dev"
        - "traefik.http.services.smtp4dev.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik3"
      resources:
        limits:
          memory: 128m

  keycloak:
    image: $REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    networks:
      - traefik3
    extra_hosts:
      - "mariadb:192.168.57.79"
    command: [ "start", "--proxy=edge" ]
    user: 1000:0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb
      - KC_DB_URL_PORT=3306
      - KC_DB_URL_DATABASE=sso
      - KC_DB_USERNAME=sso
      - KC_DB_PASSWORD=sso
      - KC_LOG_LEVEL=DEBUG
      - KC_LOG_CONSOLE_COLOR=true
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME_DEBUG=true
#      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8787,server=y,suspend=n"
      - KC_CACHE=ispn
      - KC_CACHE_CONFIG_FILE=cache-ispn-custom.xml
#    healthcheck:
#      test: [
#        "CMD-SHELL",
#        'exec 3<>/dev/tcp/localhost/9000;
#           echo -e "GET /health/ready HTTP/1.1\nhost: localhost:9000\n" >&3; 
#           timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; 
#           ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
#      ]
#      interval: 5s
#      retries: 36
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.http8k.rule=Host(`er-sso.dev.it-resource.team`) && PathPrefix(`/`)"
        - "traefik.http.routers.http8k.service=http8k-service"
        - "traefik.http.services.http8k-service.loadbalancer.server.port=8080"
        - "traefik.http.routers.http9k.rule=Host(`er-sso-mgmt.dev.it-resource.team`) && PathPrefix(`/`)"
        - "traefik.http.routers.http9k.service=http9k-service"
        - "traefik.http.services.http9k-service.loadbalancer.server.port=9000"
        - "traefik.docker.network=traefik3"
      resources:
        limits:
          memory: 1536m
