log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name $host to: $upstream_addr: $request $status upstream_response_time $upstream_response_time msec $msec request_time $request_time';

server {
        listen       80;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass_request_headers      on;

        proxy_connect_timeout 180;
        proxy_send_timeout    180;
        proxy_read_timeout    180;

        resolver 127.0.0.11 ipv6=off valid=5s;
        set $upstream http://keycloak:8080;

        location / {
            proxy_pass $upstream;
        }
}
