### TBAPI properties
tbapi.host=10.121.10.41
tbapi.port=26800
tbapi.secure=false
tbapi.auth.appname=SSO
tbapi.auth.username=anonymous
tbapi.customer.find.path=/api/v1/customerManagement/customerAccounts/names

### PhoneCaller properties
phoneCaller.uri.perm=http://LoGSsOIn:1LoGSsOPaSsERTH777@call-auth.cc-perm.ertelecom.ru/sso_call.php
phoneCaller.uri.voronezh=http://LoGSsOIn:1LoGSsOPaSsERTH777@call-auth.cc-voronezh.ertelecom.ru/sso_call.php

### RiasApi properties
riasApi.uri=https://hq-dev.db.ertelecom.ru:443/cgi-bin/ppo/excells/web_cabinet.get_info_unauth
riasApi.client.name=SSO
riasApi.client.salt=W2NHAYTWrfEG9fDw2MAt2TuuM7VK2K7H

### SmsSender properties
smsSender.uri=http://smsgw.ertelecom.ru:13003/cgi-bin/sendsms
smsSender.smscName=rapporto_gold
smsSender.username=ertelecom
smsSender.password=P10BxzA6Z1BRM
smsSender.senderName=Domru
smsSender.timeout=1440

### ViberSender properties
viberSender.uri=http://smsgw-prior.ertelecom.ru:13003/cgi-bin/sendsms
viberSender.smscName=rapporto_viber
viberSender.username=ertelecom
viberSender.password=P10BxzA6Z1BRM
viberSender.senderName=Domru
viberSender.timeout=5

### CitiesResource properties
cities.url=https://master.lk-backend.b2bweb.t2.ertelecom.ru/site/domains

### RiasLogin properties
riasLogin.scheme=https
riasLogin.defCity=perm-dev
riasLogin.domain=db.ertelecom.ru
riasLogin.port=443
riasLogin.path=/cgi-bin/ppo/es_webface/open_auth.authorize_password
riasLogin.client.name=WEB_CABINET_B2B
riasLogin.client.salt=kad14duh534u2h3j2mmi8dyla9dze
riasLogin.grantType=password

### Esia properties
esia.domain.url=https://esia-portal1.test.gosuslugi.ru

### vk properties
vk.auth.url=https://oauth.vk.com/authorize
vk.token.url=https://oauth.vk.com/access_token
vk.profile.url=https://api.vk.com/method/users.get
vk.default.scope=email
vk.api.version=5.101

### CustomIdpReview properties
idpReview.siteKey=6LfQG68UAAAAAOowA30NhSf4_VjiuH_KeT8bN3_B
idpReview.siteSecretValue=6LfQG68UAAAAAH8quIVwZ_8Cizgwi6CqjPIP5a3w
idpReview.recaptcha.url=https://www.google.com/recaptcha/api.js?hl=
idpReview.recaptcha.siteVerify=https://www.google.com/recaptcha/api/siteverify

### Schedule properties
application.schedule.import.milliseconds=300000
application.schedule.user.milliseconds=60000