### Auth token set
POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = {{client_id}} &
grant_type = password &
username = {{username}} &
password = {{password}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("access_token", response.body.access_token);
%}

### Find test user
GET http://localhost:8080/auth/realms/e2e/users-info/search?searchRealm=e2e&first=0&max=11&searchEmail=tester@nomail.tld
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("testerId", response.body.results['users-info'][0].id);
%}

### Find credentials
GET http://localhost:8080/auth/admin/realms/{{realm}}/users/{{testerId}}/credentials/
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("testerCredentials", response.body[0].id);
%}


### Test delete password
DELETE http://localhost:8080/auth/realms/{{realm}}/users-toms/users/{{testerId}}/credentials/{{testerCredentials}}
Authorization: Bearer {{access_token}}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
