apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infinispan.fullname" . }}
  labels:
    {{- include "infinispan.labels" . | nindent 4 }}
data:
  clustered.xml: |-
    {{- if eq .Values.site "staging" }}
    {{- ($.Files.Get "configs/clustered-staging.xml") | nindent 4 }}
    {{- end }}