apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infinispan.fullname" . }}-config
  labels:
    {{- include "infinispan.labels" . | nindent 4 }}
stringData:
  mgmt-users.properties: |-
    {{- ($.Files.Get "configs/mgmt-users.properties") | nindent 4 }}
  mgmt-groups.properties: |-
    {{- ($.Files.Get "configs/mgmt-groups.properties") | nindent 4 }}