apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infinispan.fullname" . }}
  labels:
    {{- include "infinispan.labels" . | nindent 4 }}
stringData:
  application-password: {{ .Values.credentials.user }}
  application-user: {{ .Values.credentials.password }}