apiVersion: v1
kind: Service
metadata:
  name: {{ include "infinispan.fullname" . }}-headless
  labels:
    {{- include "infinispan.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: hotrod
      port: 12222
      targetPort: 12222
    - name: rest
      port: 9080
      targetPort: 9080
    - name: ping
      port: 8888
      targetPort: 8888
    - name: jgroups-tcp
      port: 7601
      targetPort: 7601
  selector:
    {{- include "infinispan.selectorLabels" . | nindent 4 }}