apiVersion: v1
kind: Service
metadata:
  name: {{ include "infinispan.fullname" . }}-http
  labels:
    {{- include "infinispan.labels" . | nindent 4 }}  
spec:
  type: {{ .Values.managementService.type }}
  {{- if and (eq "LoadBalancer" .Values.managementService.type) .Values.managementService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.managementService.loadBalancerIP }}
  {{- end }}
  ports:
    - name: rest
      port: {{ .Values.managementService.restPort }}
      targetPort: 9080
      {{- if and (eq "NodePort" .Values.managementService.type) .Values.managementService.restNodePort }}
      nodePort: {{ .Values.managementService.restNodePort }}
      {{- end }}
      protocol: TCP
    - name: management
      port: {{ .Values.managementService.managementPort }}
      targetPort: 9990
      {{- if and (eq "NodePort" .Values.managementService.type) .Values.managementService.managementNodePort }}
      nodePort: {{ .Values.managementService.managementNodePort }}
      {{- end }}
      protocol: TCP
    {{- with .Values.managementService.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{ include "infinispan.selectorLabels" . | nindent 4 }}