apiVersion: v1
kind: Service
metadata:
  name: {{ include "infinispan.fullname" . }}-hotrod
  labels:
    {{- include "infinispan.labels" . | nindent 4 }}
spec:
  ports:
    - name: hotrod
      port: 12222
      targetPort: 12222
  selector:
    {{ include "infinispan.selectorLabels" . | nindent 4 }}