server {
    listen 443 ssl;
    server_name localhost stelecom.local ertelecom.local;
    ssl_certificate /etc/nginx/ssl/default/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/default/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location / {
        # proxy_set_header X-Forwarded-Host $http_host; # не передается на продуктиве
        proxy_set_header host $http_host;
        proxy_set_header x-forwarded-proto https;
        proxy_pass http://host.docker.internal:8080;
    }
}
