server {
    listen 80;
    server_name localhost;
    include /etc/nginx/mime.types;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
    location /keycloak {
        rewrite /keycloak(/|$)(.*) /$2 break;
        proxy_set_body $request_body&client_secret=secret;
        proxy_pass http://host.docker.internal:8080;
    }
}
