server {
    listen 8180;
    server_name localhost;
    include /etc/nginx/mime.types;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
    location /keycloak {
        rewrite /keycloak(/|$)(.*) /$2 break;
        proxy_set_body $request_body&client_secret=secret;
        proxy_pass http://host.docker.internal:8080;
    }
}
server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate /etc/nginx/ssl/default/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/default/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location / {
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-Host localhost;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://host.docker.internal:8080;
    }
}