dependencies {
    compileOnly "org.keycloak:keycloak-dependencies-server-all:$keycloakVersion"
    compileOnly "org.keycloak:keycloak-core:$keycloakVersion"

    implementation(platform("io.quarkus:quarkus-bom:$quarkusVersion"))
    compileOnly "io.quarkus:quarkus-core"
    compileOnly "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    implementation "org.hibernate.validator:hibernate-validator"
    implementation "org.glassfish.expressly:expressly"

    implementation "org.apache.poi:poi:5.3.0"
    implementation "org.apache.poi:poi-ooxml:5.3.0"
    implementation "com.opencsv:opencsv:5.9"
    implementation "org.jsoup:jsoup:1.18.1"
    implementation "com.helger:ph-css:7.0.2"

    implementation (
            project(":custom-jpa-provider"),
    )

    testImplementation "org.keycloak:keycloak-dependencies-server-all:$keycloakVersion"
    testImplementation "org.keycloak:keycloak-core:$keycloakVersion"
}
