dependencies {
    compileOnly "org.keycloak:keycloak-quarkus-server-app:$keycloakVersion"

    implementation(platform("io.quarkus:quarkus-bom:$quarkusVersion"))
    implementation "org.hibernate.validator:hibernate-validator"
    implementation ("org.glassfish.expressly:expressly") {
        exclude group: 'jakarta.el', module: 'jakarta.el-api'
    }

    implementation ("org.apache.poi:poi:5.3.0") {
        exclude group: 'commons-codec', module: 'commons-codec'
        exclude group: 'commons-io', module: 'commons-io'
        exclude group: 'org.apache.commons', module: 'commons-collections4'
    }
    implementation ("org.apache.poi:poi-ooxml:5.3.0") {
        exclude group: 'commons-codec', module: 'commons-codec'
        exclude group: 'commons-io', module: 'commons-io'
        exclude group: 'org.apache.commons', module: 'commons-collections4'
        exclude group: 'org.apache.commons', module: 'commons-lang3'
    }
    implementation ("com.opencsv:opencsv:5.9") {
        exclude group: 'org.apache.commons', module: 'commons-collections4'
        exclude group: 'org.apache.commons', module: 'commons-lang3'
    }
    implementation "org.jsoup:jsoup:1.18.1"
    implementation ("com.helger:ph-css:7.0.2") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }

    implementation (
            project(":custom-jpa-provider"),
    )

    testImplementation "org.keycloak:keycloak-quarkus-server-app:$keycloakVersion"
}
