### TBAPI properties
tbapi.host=10.121.10.41
tbapi.port=26800
tbapi.secure=false
tbapi.auth.appname=SSO
tbapi.auth.username=anonymous
tbapi.customer.find.path=/api/v1/customerManagement/customerAccounts/names

### PhoneCaller properties
phoneCaller.uri.perm=http://LoGSsOIn:1LoGSsOPaSsERTH777@call-auth.cc-perm.ertelecom.ru/sso_call.php
phoneCaller.uri.voronezh=http://LoGSsOIn:1LoGSsOPaSsERTH777@call-auth.cc-voronezh.ertelecom.ru/sso_call.php

### RiasApi properties
riasApi.uri=https://hq-dev.db.ertelecom.ru:443/cgi-bin/ppo/excells/web_cabinet.get_info_unauth
riasApi.client.name=SSO
riasApi.client.salt=W2NHAYTWrfEG9fDw2MAt2TuuM7VK2K7H

### SmsSender properties
smsSender.uri=http://smsgw.ertelecom.ru:13003/cgi-bin/sendsms
smsSender.smscName=rapporto_gold
smsSender.username=ertelecom
smsSender.password=P10BxzA6Z1BRM
smsSender.senderName=Domru

### ViberSender properties
viberSender.uri=http://smsgw-prior.ertelecom.ru:13003/cgi-bin/sendsms
viberSender.smscName=rapporto_viber
viberSender.username=ertelecom
viberSender.password=P10BxzA6Z1BRM
viberSender.senderName=Domru