user.absence.notifications.days=30
user.absence.blocking.days=30

application.host=http://domru-sso.alamics.local

### TBAPI properties
tbapi.host=10.121.10.41
tbapi.port=26800
tbapi.secure=false
tbapi.auth.appname=SSO
tbapi.auth.username=anonymous
tbapi.customer.find.path=/api/v1/customerManagement/customerAccounts/names
tbapi.customer.request.max.size=10
tbapi.customer.request.interval.milliseconds=10000
tbapi.customer.request.load.coeff=100

user.post.cache.db.lifespan.days=1