user.absence.notifications.days=30
user.absence.blocking.days=30

### TBAPI properties
tbapi.host=tb-app01.int.bss.loc
tbapi.port=26300
tbapi.secure=true
tbapi.auth.appname=SSP
tbapi.auth.username=anonymous
tbapi.customer.find.path=/api/v1/customerManagement/customerAccount/{customerIds}/names