user.absence.notifications.days=30
user.absence.blocking.days=30

application.host=http://domru-sso.alamics.local

### TBAPI properties
tbapi.host=10.121.10.41
tbapi.port=26800
tbapi.secure=false
tbapi.auth.appname=SSO
tbapi.auth.username=anonymous
tbapi.customer.find.path=/api/v1/customerManagement/customerAccounts/names