quarkus:
  datasource:
    jdbc:
      url: jdbc:mariadb://${KC_DB_URL_HOST:localhost}:${KC_DB_URL_PORT:3306}/${DB_DATABASE:sso}
    username: ${KC_DB_USERNAME:sso}
    password: ${KC_DB_PASSWORD:sso}
    db-kind: mariadb
  infinispan-client:
    hosts: ${KC_CACHE_REMOTE_HOST:localhost}:${KC_CACHE_REMOTE_PORT:11222}
    username: ${KC_CACHE_REMOTE_USERNAME:keycloak}
    password: ${KC_CACHE_REMOTE_PASSWORD:keycloak}
  devservices:
    enabled: false
