---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: customercache
  namespace: infinispan
spec:
  clusterName: infinispan
  name: customer_cache
  #language=yaml
  template: |-
    replicatedCache: 
      mode: "SYNC"
      remoteTimeout: "61000"
      statistics: "true"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking: 
        acquireTimeout: "60000"
      transaction: 
        mode: "NON_XA"
        locking: "PESSIMISTIC"
      expiration: 
        lifespan: "500000"
        maxIdle: "100000"
      stateTransfer: 
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: userpostcache
  namespace: infinispan
spec:
  clusterName: infinispan
  name: user_post_cache
  #language=yaml
  template: |-
    replicatedCache: 
      mode: "SYNC"
      remoteTimeout: "61000"
      statistics: "true"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking: 
        acquireTimeout: "60000"
      transaction: 
        mode: "NON_XA"
        locking: "PESSIMISTIC"
      expiration: 
        lifespan: "500000"
        maxIdle: "100000"
      stateTransfer: 
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: work
  namespace: infinispan
spec:
  clusterName: infinispan
  name: work
  #language=yaml
  template: |-
    replicatedCache: 
      mode: "SYNC"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking: 
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction: 
        mode: "NON_XA"
        locking: "PESSIMISTIC"
      stateTransfer: 
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: authenticationsessions
  namespace: infinispan
spec:
  clusterName: infinispan
  name: authenticationSessions
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: sessions
  namespace: infinispan
spec:
  clusterName: infinispan
  name: sessions
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: clientsessions
  namespace: infinispan
spec:
  clusterName: infinispan
  name: clientSessions
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: offlinesessions
  namespace: infinispan
spec:
  clusterName: infinispan
  name: offlineSessions
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: offlineclientsessions
  namespace: infinispan
spec:
  clusterName: infinispan
  name: offlineClientSessions
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: loginfailures
  namespace: infinispan
spec:
  clusterName: infinispan
  name: loginFailures
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: actiontokens
  namespace: infinispan
spec:
  clusterName: infinispan
  name: actionTokens
  #language=yaml
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      remoteTimeout: "61000"
      encoding:
        media-type: "application/x-jboss-marshalling"
      locking:
        acquireTimeout: "60000"
      expiration:
        lifespan: "-1"
        maxIdle: "-1"
        interval: "300000"
      transaction:
        mode: "NON_XA" 
        locking: "PESSIMISTIC" 
      stateTransfer:
        timeout: "120000"
        chunkSize: "2048"
