apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan 
  namespace: infinispan
  annotations:
    infinispan.org/monitoring: 'true' 
spec:
  replicas: 3
  version: 15.0.10
  container:
    cpu: "2000m:500m"
    memory: "4Gi:1Gi"
    extraJvmOpts: "-XX:MaxRAMPercentage=50.0 -XX:NativeMemoryTracking=summary"
  jmx:
    enabled: true
  security:
    endpointSecretName: connect-secret
  logging:
    categories:
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error
  service:
    type: DataGrid
    container:
      storage: 1Gi
      ephemeralStorage: true
