apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan 
  namespace: infinispan
  annotations:
    infinispan.org/monitoring: 'true' 
spec:
  replicas: 5
  version: 15.0.10
  container:
    cpu: "2000m:500m"
    memory: "4Gi:1Gi"
    extraJvmOpts: "-Xms1024m -Xmx4096m -XX:NativeMemoryTracking=summary"
  expose:
    type: NodePort
    nodePort: 31222
  jmx:
    enabled: true
  security:
    endpointSecretName: connect-secret
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: infinispan-pod
            clusterName: infinispan
            infinispan_cr: infinispan
        topologyKey: "topology.kubernetes.io/hostname"
  logging:
    categories:
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error
  service:
    type: DataGrid
    container:
      storage: 1Gi
      ephemeralStorage: true      
    sites:
      local:
        name: voronezh
        discovery:
          launchGossipRouter: true
          memory: "2Gi:1Gi"
          cpu: "2000m:500m"
          heartbeats:
            enabled: true
            interval: 2000
            timeout: 8000
        expose:
          type: NodePort
          nodePort: 32600
        maxRelayNodes: 5
      locations:
        - name: perm
          url: infinispan+xsite://sso-k8s-app01.cc-perm.ertelecom.ru:32600
