{{- if .Values.ingress }}
{{- $ingressApiIsStable := eq (include "sso.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "sso.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "sso.ingress.supportsPathType" .) "true" -}}
{{- range $i, $s := .Values.ingress }}
---
apiVersion: {{ include "sso.ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $i }}
  {{- with $s.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sso.labels" $ | nindent 4 }}
    {{- with $.Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName $.Values.ingressClassName }}
  ingressClassName: {{ $.Values.ingressClassName }}
  {{- end -}}
{{- if $s.tls }}
  tls:
  {{- range $s.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- range $s.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .paths | quote }}
            {{- if $ingressSupportsPathType }}
            {{- if $s.pathType}}
            pathType: {{ $s.pathType }}            
            {{- else }}
            pathType: ImplementationSpecific
            {{- end }}
            {{- end }}
            backend:
        {{- if $ingressApiIsStable }}
        {{- if $s.external_service }}
              service:
                name: {{ $s.external_service.name }}
                port:
                  number: {{ $s.external_service.port }}
        {{- else }}
              service:
                name: {{ include "sso.fullname" $ }}-http
                port:
                  number: {{ $.Values.service.httpPort }}
        {{- end }}
        {{- else }}
        {{- if $s.external_service }}
              serviceName: {{ $s.external_service.name }}
              servicePort: {{ $s.external_service.port }}
        {{- else }}
              serviceName: {{ $.Release.Name }}
              servicePort: {{ $.Values.service.httpPort }}
        {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
