{{- if .Values.extraSensitiveEnvs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso.fullname" . }}
  labels:
    {{- include "sso.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.extraSensitiveEnvs | nindent 2 }}
{{- end }}