{{- if .Values.monitoring.authMetrics }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sso.fullname" . }}-monitor
  labels:
    {{- include "sso.labels" . | nindent 4 }}
spec:
  endpoints:
    - honorLabels: true
      interval: 15s
      path: /auth/metrics
      port: http-management
      scheme: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "sso.labels" . | nindent 6 }}
{{- end }}
